apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: monitoring-tools
  labels:
    name: grafana
spec:
  selector:
    app: zipkin
  ports:
    - name: zipkin
      port: 9411
      targetPort: 9411
  type: LoadBalancer
