apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-httpproxy
  namespace: minio
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: minio-svc
      port: 80
  virtualhost:
    fqdn: minio.tanzudata.ml
