apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petclinic-YOUR_SESSION_NAMESPACE-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: petclinic-app
      port: 80
  virtualhost:
    fqdn: petclinic-YOUR_SESSION_NAMESPACE.tanzudata.ml
